// flow-typed signature: b02ab8da54101522d477090be728d104
// flow-typed version: <<STUB>>/react-native-popup-dialog_v^0.17.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-popup-dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-popup-dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-popup-dialog/__tests__/Dialog.test' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/__tests__/DialogTitle.test' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/__tests__/setup-tests' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/animations/Animation' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/animations/FadeAnimation' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/animations/ScaleAnimation' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/animations/SlideAnimation' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/components/Dialog' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/components/DialogButton' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/components/DialogContent' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/components/DialogFooter' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/components/DialogTitle' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/components/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/constants/Constants' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/PopupDialog' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/dist/type' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/popup-dialog-example/App' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/popup-dialog-example/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/animations/Animation' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/animations/FadeAnimation' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/animations/ScaleAnimation' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/animations/SlideAnimation' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/components/Dialog' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/components/DialogButton' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/components/DialogContent' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/components/DialogFooter' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/components/DialogTitle' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/components/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/constants/Constants' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/index' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/PopupDialog' {
  declare module.exports: any;
}

declare module 'react-native-popup-dialog/src/type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-popup-dialog/__tests__/Dialog.test.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/__tests__/Dialog.test'>;
}
declare module 'react-native-popup-dialog/__tests__/DialogTitle.test.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/__tests__/DialogTitle.test'>;
}
declare module 'react-native-popup-dialog/__tests__/setup-tests.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/__tests__/setup-tests'>;
}
declare module 'react-native-popup-dialog/dist/animations/Animation.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/animations/Animation'>;
}
declare module 'react-native-popup-dialog/dist/animations/FadeAnimation.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/animations/FadeAnimation'>;
}
declare module 'react-native-popup-dialog/dist/animations/ScaleAnimation.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/animations/ScaleAnimation'>;
}
declare module 'react-native-popup-dialog/dist/animations/SlideAnimation.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/animations/SlideAnimation'>;
}
declare module 'react-native-popup-dialog/dist/components/Dialog.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/components/Dialog'>;
}
declare module 'react-native-popup-dialog/dist/components/DialogButton.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/components/DialogButton'>;
}
declare module 'react-native-popup-dialog/dist/components/DialogContent.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/components/DialogContent'>;
}
declare module 'react-native-popup-dialog/dist/components/DialogFooter.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/components/DialogFooter'>;
}
declare module 'react-native-popup-dialog/dist/components/DialogTitle.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/components/DialogTitle'>;
}
declare module 'react-native-popup-dialog/dist/components/Overlay.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/components/Overlay'>;
}
declare module 'react-native-popup-dialog/dist/constants/Constants.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/constants/Constants'>;
}
declare module 'react-native-popup-dialog/dist/index.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/index'>;
}
declare module 'react-native-popup-dialog/dist/PopupDialog.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/PopupDialog'>;
}
declare module 'react-native-popup-dialog/dist/type.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/dist/type'>;
}
declare module 'react-native-popup-dialog/popup-dialog-example/App.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/popup-dialog-example/App'>;
}
declare module 'react-native-popup-dialog/popup-dialog-example/babel.config.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/popup-dialog-example/babel.config'>;
}
declare module 'react-native-popup-dialog/src/animations/Animation.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/animations/Animation'>;
}
declare module 'react-native-popup-dialog/src/animations/FadeAnimation.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/animations/FadeAnimation'>;
}
declare module 'react-native-popup-dialog/src/animations/ScaleAnimation.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/animations/ScaleAnimation'>;
}
declare module 'react-native-popup-dialog/src/animations/SlideAnimation.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/animations/SlideAnimation'>;
}
declare module 'react-native-popup-dialog/src/components/Dialog.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/components/Dialog'>;
}
declare module 'react-native-popup-dialog/src/components/DialogButton.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/components/DialogButton'>;
}
declare module 'react-native-popup-dialog/src/components/DialogContent.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/components/DialogContent'>;
}
declare module 'react-native-popup-dialog/src/components/DialogFooter.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/components/DialogFooter'>;
}
declare module 'react-native-popup-dialog/src/components/DialogTitle.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/components/DialogTitle'>;
}
declare module 'react-native-popup-dialog/src/components/Overlay.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/components/Overlay'>;
}
declare module 'react-native-popup-dialog/src/constants/Constants.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/constants/Constants'>;
}
declare module 'react-native-popup-dialog/src/index.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/index'>;
}
declare module 'react-native-popup-dialog/src/PopupDialog.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/PopupDialog'>;
}
declare module 'react-native-popup-dialog/src/type.js' {
  declare module.exports: $Exports<'react-native-popup-dialog/src/type'>;
}
