// flow-typed signature: dfeaae3f100d487591c0afdba2f78230
// flow-typed version: <<STUB>>/@storybook/core_v^4.1.11/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/core/client' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/index' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/manager/index' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/manager/preview' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/manager/provider' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/client_api' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/client_api.test' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/config_api' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/reducer' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/start' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/start.test' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/story_store' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/story_store.test' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/subscriptions_store' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/subscriptions_store.test' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/client/preview/syncUrlWithStore' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/build-dev' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/build-static' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/cli/dev' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/cli/index' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/cli/prod' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/cli/utils' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/common/babel-cache-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/common/babel-loader' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/common/babel' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/common/common-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/common/custom-presets' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/common/polyfills' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/config/utils' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/dev-server' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/manager/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/manager/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/manager/manager-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/presets' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/presets.test' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/preview/base-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/preview/custom-webpack-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/preview/entries' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/preview/globals' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/preview/iframe-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/preview/preview-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/standalone' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/interpret-files' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/interpret-files.test' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/load-custom-addons-file' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/load-custom-babel-config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/load-custom-config-file' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/load-custom-webpack-config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/merge-webpack-config' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/merge-webpack-config.test' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/middleware' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/server-require' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/template' {
  declare module.exports: any;
}

declare module '@storybook/core/dist/server/utils/template.test' {
  declare module.exports: any;
}

declare module '@storybook/core/dll/storybook_ui_dll' {
  declare module.exports: any;
}

declare module '@storybook/core/server' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/index' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/manager/index' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/manager/preview' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/manager/provider' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/client_api' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/client_api.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/config_api' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/reducer' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/start' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/start.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/story_store' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/story_store.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/subscriptions_store' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/subscriptions_store.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/client/preview/syncUrlWithStore' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/build-dev' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/build-static' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/cli/dev' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/cli/index' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/cli/prod' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/cli/utils' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/common/babel-cache-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/common/babel-loader' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/common/babel' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/common/common-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/common/custom-presets' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/common/polyfills' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/config/utils' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/dev-server' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/manager/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/manager/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/manager/manager-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/presets' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/presets.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/preview/base-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/preview/custom-webpack-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/preview/entries' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/preview/globals' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/preview/iframe-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/preview/preview-preset' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/standalone' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/interpret-files' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/interpret-files.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/load-custom-addons-file' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/load-custom-babel-config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/load-custom-config-file' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/load-custom-webpack-config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/merge-webpack-config' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/merge-webpack-config.test' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/middleware' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/server-require' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/template' {
  declare module.exports: any;
}

declare module '@storybook/core/src/server/utils/template.test' {
  declare module.exports: any;
}

declare module '@storybook/core/standalone' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/core/client.js' {
  declare module.exports: $Exports<'@storybook/core/client'>;
}
declare module '@storybook/core/dist/client/index.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/index'>;
}
declare module '@storybook/core/dist/client/manager/index.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/manager/index'>;
}
declare module '@storybook/core/dist/client/manager/preview.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/manager/preview'>;
}
declare module '@storybook/core/dist/client/manager/provider.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/manager/provider'>;
}
declare module '@storybook/core/dist/client/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/actions'>;
}
declare module '@storybook/core/dist/client/preview/client_api.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/client_api'>;
}
declare module '@storybook/core/dist/client/preview/client_api.test.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/client_api.test'>;
}
declare module '@storybook/core/dist/client/preview/config_api.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/config_api'>;
}
declare module '@storybook/core/dist/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/index'>;
}
declare module '@storybook/core/dist/client/preview/reducer.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/reducer'>;
}
declare module '@storybook/core/dist/client/preview/start.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/start'>;
}
declare module '@storybook/core/dist/client/preview/start.test.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/start.test'>;
}
declare module '@storybook/core/dist/client/preview/story_store.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/story_store'>;
}
declare module '@storybook/core/dist/client/preview/story_store.test.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/story_store.test'>;
}
declare module '@storybook/core/dist/client/preview/subscriptions_store.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/subscriptions_store'>;
}
declare module '@storybook/core/dist/client/preview/subscriptions_store.test.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/subscriptions_store.test'>;
}
declare module '@storybook/core/dist/client/preview/syncUrlWithStore.js' {
  declare module.exports: $Exports<'@storybook/core/dist/client/preview/syncUrlWithStore'>;
}
declare module '@storybook/core/dist/server/build-dev.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/build-dev'>;
}
declare module '@storybook/core/dist/server/build-static.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/build-static'>;
}
declare module '@storybook/core/dist/server/cli/dev.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/cli/dev'>;
}
declare module '@storybook/core/dist/server/cli/index.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/cli/index'>;
}
declare module '@storybook/core/dist/server/cli/prod.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/cli/prod'>;
}
declare module '@storybook/core/dist/server/cli/utils.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/cli/utils'>;
}
declare module '@storybook/core/dist/server/common/babel-cache-preset.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/common/babel-cache-preset'>;
}
declare module '@storybook/core/dist/server/common/babel-loader.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/common/babel-loader'>;
}
declare module '@storybook/core/dist/server/common/babel.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/common/babel'>;
}
declare module '@storybook/core/dist/server/common/common-preset.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/common/common-preset'>;
}
declare module '@storybook/core/dist/server/common/custom-presets.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/common/custom-presets'>;
}
declare module '@storybook/core/dist/server/common/polyfills.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/common/polyfills'>;
}
declare module '@storybook/core/dist/server/config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config'>;
}
declare module '@storybook/core/dist/server/config/utils.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/config/utils'>;
}
declare module '@storybook/core/dist/server/dev-server.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/dev-server'>;
}
declare module '@storybook/core/dist/server/manager/manager-config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/manager/manager-config'>;
}
declare module '@storybook/core/dist/server/manager/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/manager/manager-preset'>;
}
declare module '@storybook/core/dist/server/manager/manager-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/manager/manager-webpack.config'>;
}
declare module '@storybook/core/dist/server/presets.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/presets'>;
}
declare module '@storybook/core/dist/server/presets.test.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/presets.test'>;
}
declare module '@storybook/core/dist/server/preview/base-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/preview/base-webpack.config'>;
}
declare module '@storybook/core/dist/server/preview/custom-webpack-preset.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/preview/custom-webpack-preset'>;
}
declare module '@storybook/core/dist/server/preview/entries.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/preview/entries'>;
}
declare module '@storybook/core/dist/server/preview/globals.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/preview/globals'>;
}
declare module '@storybook/core/dist/server/preview/iframe-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/preview/iframe-webpack.config'>;
}
declare module '@storybook/core/dist/server/preview/preview-preset.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/preview/preview-preset'>;
}
declare module '@storybook/core/dist/server/standalone.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/standalone'>;
}
declare module '@storybook/core/dist/server/utils/interpret-files.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/interpret-files'>;
}
declare module '@storybook/core/dist/server/utils/interpret-files.test.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/interpret-files.test'>;
}
declare module '@storybook/core/dist/server/utils/load-custom-addons-file.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/load-custom-addons-file'>;
}
declare module '@storybook/core/dist/server/utils/load-custom-babel-config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/load-custom-babel-config'>;
}
declare module '@storybook/core/dist/server/utils/load-custom-config-file.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/load-custom-config-file'>;
}
declare module '@storybook/core/dist/server/utils/load-custom-webpack-config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/load-custom-webpack-config'>;
}
declare module '@storybook/core/dist/server/utils/merge-webpack-config.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/merge-webpack-config'>;
}
declare module '@storybook/core/dist/server/utils/merge-webpack-config.test.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/merge-webpack-config.test'>;
}
declare module '@storybook/core/dist/server/utils/middleware.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/middleware'>;
}
declare module '@storybook/core/dist/server/utils/server-require.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/server-require'>;
}
declare module '@storybook/core/dist/server/utils/template.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/template'>;
}
declare module '@storybook/core/dist/server/utils/template.test.js' {
  declare module.exports: $Exports<'@storybook/core/dist/server/utils/template.test'>;
}
declare module '@storybook/core/dll/storybook_ui_dll.js' {
  declare module.exports: $Exports<'@storybook/core/dll/storybook_ui_dll'>;
}
declare module '@storybook/core/server.js' {
  declare module.exports: $Exports<'@storybook/core/server'>;
}
declare module '@storybook/core/src/client/index.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/index'>;
}
declare module '@storybook/core/src/client/manager/index.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/manager/index'>;
}
declare module '@storybook/core/src/client/manager/preview.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/manager/preview'>;
}
declare module '@storybook/core/src/client/manager/provider.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/manager/provider'>;
}
declare module '@storybook/core/src/client/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/actions'>;
}
declare module '@storybook/core/src/client/preview/client_api.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/client_api'>;
}
declare module '@storybook/core/src/client/preview/client_api.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/client_api.test'>;
}
declare module '@storybook/core/src/client/preview/config_api.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/config_api'>;
}
declare module '@storybook/core/src/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/index'>;
}
declare module '@storybook/core/src/client/preview/reducer.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/reducer'>;
}
declare module '@storybook/core/src/client/preview/start.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/start'>;
}
declare module '@storybook/core/src/client/preview/start.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/start.test'>;
}
declare module '@storybook/core/src/client/preview/story_store.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/story_store'>;
}
declare module '@storybook/core/src/client/preview/story_store.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/story_store.test'>;
}
declare module '@storybook/core/src/client/preview/subscriptions_store.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/subscriptions_store'>;
}
declare module '@storybook/core/src/client/preview/subscriptions_store.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/subscriptions_store.test'>;
}
declare module '@storybook/core/src/client/preview/syncUrlWithStore.js' {
  declare module.exports: $Exports<'@storybook/core/src/client/preview/syncUrlWithStore'>;
}
declare module '@storybook/core/src/server/build-dev.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/build-dev'>;
}
declare module '@storybook/core/src/server/build-static.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/build-static'>;
}
declare module '@storybook/core/src/server/cli/dev.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/cli/dev'>;
}
declare module '@storybook/core/src/server/cli/index.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/cli/index'>;
}
declare module '@storybook/core/src/server/cli/prod.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/cli/prod'>;
}
declare module '@storybook/core/src/server/cli/utils.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/cli/utils'>;
}
declare module '@storybook/core/src/server/common/babel-cache-preset.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/common/babel-cache-preset'>;
}
declare module '@storybook/core/src/server/common/babel-loader.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/common/babel-loader'>;
}
declare module '@storybook/core/src/server/common/babel.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/common/babel'>;
}
declare module '@storybook/core/src/server/common/common-preset.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/common/common-preset'>;
}
declare module '@storybook/core/src/server/common/custom-presets.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/common/custom-presets'>;
}
declare module '@storybook/core/src/server/common/polyfills.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/common/polyfills'>;
}
declare module '@storybook/core/src/server/config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config'>;
}
declare module '@storybook/core/src/server/config/utils.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/config/utils'>;
}
declare module '@storybook/core/src/server/dev-server.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/dev-server'>;
}
declare module '@storybook/core/src/server/manager/manager-config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/manager/manager-config'>;
}
declare module '@storybook/core/src/server/manager/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/manager/manager-preset'>;
}
declare module '@storybook/core/src/server/manager/manager-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/manager/manager-webpack.config'>;
}
declare module '@storybook/core/src/server/presets.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/presets'>;
}
declare module '@storybook/core/src/server/presets.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/presets.test'>;
}
declare module '@storybook/core/src/server/preview/base-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/preview/base-webpack.config'>;
}
declare module '@storybook/core/src/server/preview/custom-webpack-preset.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/preview/custom-webpack-preset'>;
}
declare module '@storybook/core/src/server/preview/entries.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/preview/entries'>;
}
declare module '@storybook/core/src/server/preview/globals.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/preview/globals'>;
}
declare module '@storybook/core/src/server/preview/iframe-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/preview/iframe-webpack.config'>;
}
declare module '@storybook/core/src/server/preview/preview-preset.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/preview/preview-preset'>;
}
declare module '@storybook/core/src/server/standalone.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/standalone'>;
}
declare module '@storybook/core/src/server/utils/interpret-files.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/interpret-files'>;
}
declare module '@storybook/core/src/server/utils/interpret-files.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/interpret-files.test'>;
}
declare module '@storybook/core/src/server/utils/load-custom-addons-file.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/load-custom-addons-file'>;
}
declare module '@storybook/core/src/server/utils/load-custom-babel-config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/load-custom-babel-config'>;
}
declare module '@storybook/core/src/server/utils/load-custom-config-file.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/load-custom-config-file'>;
}
declare module '@storybook/core/src/server/utils/load-custom-webpack-config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/load-custom-webpack-config'>;
}
declare module '@storybook/core/src/server/utils/merge-webpack-config.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/merge-webpack-config'>;
}
declare module '@storybook/core/src/server/utils/merge-webpack-config.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/merge-webpack-config.test'>;
}
declare module '@storybook/core/src/server/utils/middleware.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/middleware'>;
}
declare module '@storybook/core/src/server/utils/server-require.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/server-require'>;
}
declare module '@storybook/core/src/server/utils/template.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/template'>;
}
declare module '@storybook/core/src/server/utils/template.test.js' {
  declare module.exports: $Exports<'@storybook/core/src/server/utils/template.test'>;
}
declare module '@storybook/core/standalone.js' {
  declare module.exports: $Exports<'@storybook/core/standalone'>;
}
